export interface Order {

  id: number;

  customerId: number;

  customerName: string;

  productId: number[];

  productName: string[];

  quantity: number;

  totalAmount: number;

  orderDate: string;
    syncStatus: 'PENDING' | 'SYNCED' | 'FAILED'| 'SYNCING'| 'NOT_SYNCED'| 'SYNC_IN_PROGRESS' | 'SYNC_FAILED' | 'SYNC_SUCCESS' | 'SYNC_PENDING' | 'SYNC_NOT_STARTED' | 'SYNC_NOT_REQUIRED' | 'SYNC_NOT_APPLICABLE' | 'SYNC_NOT_SUPPORTED' | 'SYNC_NOT_AVAILABLE' | 'SYNC_NOT_ALLOWED' | 'SYNC_NOT_AUTHORIZED' | 'SYNC_NOT_FOUND' | 'SYNC_NOT_IMPLEMENTED' | 'SYNC_NOT_SUPPORTED_ON_PLATFORM' | 'SYNC_NOT_SUPPORTED_ON_DEVICE' | 'SYNC_NOT_SUPPORTED_ON_BROWSER' | 'SYNC_NOT_SUPPORTED_ON_OS' | 'SYNC_NOT_SUPPORTED_ON_VERSION' | 'SYNC_NOT_SUPPORTED_ON_ARCHITECTURE' | 'SYNC_NOT_SUPPORTED_ON_HARDWARE' | 'SYNC_NOT_SUPPORTED_ON_SOFTWARE' | 'SYNC_NOT_SUPPORTED_ON_NETWORK' | 'SYNC_NOT_SUPPORTED_ON_STORAGE' | 'SYNC_NOT_SUPPORTED_ON_MEMORY' | 'SYNC_NOT_SUPPORTED_ON_CPU' | 'SYNC_NOT_SUPPORTED_ON_GPU';

}